# Generated by Django 5.0.1 on 2024-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
